### ISSUE TITLE
 NetflixAuthError('There was a problem retrieving an authentication url')

### ISSUE THREAD

**Issue by kurttheviking** [michaelhelmick/python-netflix#5]
When I installed from pip I got this error when setting up an API connection. However, I cloned the repo to see if I could debug and it worked fine. Maybe PIP just needs to be updated?

**Comment by michaelhelmick** [comment]
Can you check the version on the one you installed from pip compared to the one you cloned from GitHub?  

Thanks  

## 

Mike Helmick
