### ISSUE TITLE
the example from main page doesn't work

### ISSUE THREAD

**Issue by lega911** [michaelhelmick/python-netflix#6]
Exception:
    from requests.auth import OAuth1
ImportError: cannot import name OAuth1

**Comment by michaelhelmick** [comment]
It's because you have the latest version of `requests`.
In my `setup.py` I have requests>=0.14.0 or something like that, so it's giving you `requests` 1.1.0 probably.

Try running this code in terminal
`pip install -I requests==0.14.0` (you may need sudo pip install)

It should fix your problem.
